[server]
connect = 1
address = 127.0.0.1
port = 8888

[model]
# Only used if connect = 0 (local mode)
type = SINDYc
file = data/SINDYc_tiegcm_hrd.h5

[transformer]
# Only used if connect = 0 (local mode)
type = PCA
file = data/PCA_tiegcm_hrd.h5

[solver]
# only used if connect = 0 (local mode)
timestep = 0.5
kp_index = 0