#!/usr/bin/env bash
# DeployDemo.sh — end-to-end ROPE deployment demo.
#
# Steps:
#   1. Build the Docker image (if needed)
#   2. Write a runtime config (socket mode) into a tmpdir
#   3. Launch the container; wait for the forecast to finish and the socket
#      to appear
#   4. Connect to the socket, send a batch of density queries (including one
#      intentional out-of-range request to demonstrate error handling)
#   5. Close the connection, stop the container, and clean up
#
# Environment overrides (set before calling the script):
#   IMAGE            Docker image name  (default: rope:latest)
#   FORECAST_START   Forecast start     (default: 2024-02-09 00:00:00)
#   FORECAST_HORIZON Forecast hours     (default: 120)
#   SOCKET_TIMEOUT   Seconds to wait for socket to appear (default: 120)
#   NO_BUILD         Set to 1 to skip the docker build step
#
# Usage:
#   ./DeployDemo.sh
#   IMAGE=rope:prebuilt NO_BUILD=1 ./DeployDemo.sh

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
IMAGE="${IMAGE:-rope:latest}"
CONTAINER_NAME="rope-demo-$$"
FORECAST_START="${FORECAST_START:-2024-02-09 00:00:00}"
FORECAST_HORIZON="${FORECAST_HORIZON:-120}"
SOCKET_TIMEOUT="${SOCKET_TIMEOUT:-120}"
NO_BUILD="${NO_BUILD:-0}"

# ---------------------------------------------------------------------------
# Terminal colours
# ---------------------------------------------------------------------------
if [ -t 1 ] && command -v tput &>/dev/null && tput colors &>/dev/null; then
    C_RESET="$(tput sgr0)"
    C_BOLD="$(tput bold)"
    C_BLUE="$(tput setaf 4)"
    C_GREEN="$(tput setaf 2)"
    C_YELLOW="$(tput setaf 3)"
    C_RED="$(tput setaf 1)"
    C_CYAN="$(tput setaf 6)"
else
    C_RESET="" C_BOLD="" C_BLUE="" C_GREEN="" C_YELLOW="" C_RED="" C_CYAN=""
fi

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
step()  { echo "${C_BOLD}${C_BLUE}==> Step $1:${C_RESET} ${C_BOLD}$2${C_RESET}"; }
ok()    { echo "    ${C_GREEN}✓${C_RESET}  $*"; }
info()  { echo "    ${C_CYAN}·${C_RESET}  $*"; }
warn()  { echo "    ${C_YELLOW}!${C_RESET}  $*"; }
die()   { echo "${C_RED}${C_BOLD}ERROR:${C_RESET} $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Cleanup on exit
# ---------------------------------------------------------------------------
TMPDIR_DEMO=""
cleanup() {
    local exit_code=$?
    if [ -n "$(docker ps -q -f name="^${CONTAINER_NAME}$" 2>/dev/null)" ]; then
        echo ""
        info "Stopping container ${CONTAINER_NAME}..."
        docker stop "${CONTAINER_NAME}" >/dev/null 2>&1 || true
        ok "Container stopped."
    fi
    if [ -n "${TMPDIR_DEMO}" ] && [ -d "${TMPDIR_DEMO}" ]; then
        rm -rf "${TMPDIR_DEMO}"
    fi
    if [ "$exit_code" -ne 0 ]; then
        echo ""
        die "Demo failed (exit code ${exit_code})."
    fi
}
trap cleanup EXIT

# ===========================================================================
# Step 1 — Build Docker image
# ===========================================================================
step 1 "Build Docker image"

if [ "${NO_BUILD}" = "1" ]; then
    warn "NO_BUILD=1 — skipping build step."
    if ! docker image inspect "${IMAGE}" &>/dev/null; then
        die "Image '${IMAGE}' not found locally. Run without NO_BUILD=1 to build it."
    fi
    ok "Image '${IMAGE}' found locally."
else
    info "Building image '${IMAGE}' (this compiles ROPE inside Docker)..."
    info "Standard output is suppressed; build log → /tmp/rope-build.log"
    if docker build \
            -t "${IMAGE}" \
            -f "${SCRIPT_DIR}/Dockerfile" \
            "${SCRIPT_DIR}" \
            > /tmp/rope-build.log 2>&1; then
        ok "Image '${IMAGE}' built successfully."
    else
        cat /tmp/rope-build.log >&2
        die "Docker build failed. See output above."
    fi
fi
echo ""

# ===========================================================================
# Step 2 — Prepare runtime config and socket directory
# ===========================================================================
step 2 "Prepare runtime config"

TMPDIR_DEMO="$(mktemp -d /tmp/rope-demo-XXXXXX)"
SOCK_DIR="${TMPDIR_DEMO}/socket"
mkdir -p "${SOCK_DIR}"
HOST_SOCK="${SOCK_DIR}/rope.sock"
CONTAINER_SOCK_DIR="/tmp/rope-socket"
CONTAINER_SOCK="${CONTAINER_SOCK_DIR}/rope.sock"

# Write a config that overrides mode and socket.path with absolute paths.
RUNTIME_CONF="${TMPDIR_DEMO}/rope.conf"
cat > "${RUNTIME_CONF}" <<EOF
# Auto-generated by DeployDemo.sh — do not edit.

[session]
mode = socket

[paths]
exported_dir = /app/exported
driver_csv   = /app/data/sw_celestrack_1957.csv
ic_csv       = /app/data/IC_Table_modified.csv

[socket]
path    = ${CONTAINER_SOCK}
start   = ${FORECAST_START}
horizon = ${FORECAST_HORIZON}

[threads]
intra_threads_base    = 1
intra_threads_decoder = 0
EOF

info "Config written to  ${RUNTIME_CONF}"
info "Socket directory   ${SOCK_DIR}  →  ${CONTAINER_SOCK_DIR} (in container)"
info "Forecast start     ${FORECAST_START}"
info "Forecast horizon   ${FORECAST_HORIZON} h"
ok "Runtime config ready."
echo ""

# ===========================================================================
# Step 3 — Launch the container
# ===========================================================================
step 3 "Launch container"

# Build docker run arguments.
DOCKER_ARGS=(
    --rm
    --detach
    --name "${CONTAINER_NAME}"
    # Run as the current user so socket files are created with matching ownership.
    --user "$(id -u):$(id -g)"
    # Mount the socket directory so both host and container share the .sock file.
    -v "${SOCK_DIR}:${CONTAINER_SOCK_DIR}"
    # Mount the runtime config over the default one.
    -v "${RUNTIME_CONF}:/app/config/rope.conf:ro"
)

# Mount model/data directories if they exist locally; otherwise assume baked in.
if [ -d "${SCRIPT_DIR}/exported" ]; then
    DOCKER_ARGS+=(-v "${SCRIPT_DIR}/exported:/app/exported:ro")
    info "Mounting exported/ from host."
else
    info "exported/ not found locally — using image copy."
fi
if [ -d "${SCRIPT_DIR}/data" ]; then
    DOCKER_ARGS+=(-v "${SCRIPT_DIR}/data:/app/data:ro")
    info "Mounting data/ from host."
else
    info "data/ not found locally — using image copy."
fi

info "Running:  docker run ${DOCKER_ARGS[*]} ${IMAGE}"
CONTAINER_ID=$(docker run "${DOCKER_ARGS[@]}" "${IMAGE}")
info "Container ID  ${CONTAINER_ID:0:12}"
info "Waiting for forecast to complete and socket to appear..."
info "(This normally takes 10–30 s depending on hardware.)"
echo ""

# Poll for the socket file; tail the container log while waiting.
WAIT_START=$(date +%s)
DOTS=0
while true; do
    if [ -S "${HOST_SOCK}" ]; then
        break
    fi
    # Check that the container is still running.
    if ! docker ps -q -f "name=^${CONTAINER_NAME}$" | grep -q .; then
        echo ""
        warn "Container exited unexpectedly.  Last log lines:"
        docker logs --tail 30 "${CONTAINER_NAME}" 2>&1 | sed 's/^/    /' || true
        die "Container stopped before the socket appeared."
    fi
    NOW=$(date +%s)
    if [ $(( NOW - WAIT_START )) -ge "${SOCKET_TIMEOUT}" ]; then
        echo ""
        die "Timed out after ${SOCKET_TIMEOUT} s waiting for ${HOST_SOCK}"
    fi
    printf "."
    DOTS=$(( DOTS + 1 ))
    [ $(( DOTS % 60 )) -eq 0 ] && echo ""
    sleep 1
done
echo ""
ok "Socket is ready  →  ${HOST_SOCK}"

# Show the container's startup log (forecast run time, density stats, etc.).
echo ""
info "Container startup log:"
docker logs "${CONTAINER_NAME}" 2>&1 | sed 's/^/    /'
echo ""

# ===========================================================================
# Step 4 — Run density queries over the socket
# ===========================================================================
step 4 "Send density queries"

python3 - "${HOST_SOCK}" "${FORECAST_START}" "${FORECAST_HORIZON}" <<'PYEOF'
import sys
import socket
import time

SOCK_PATH   = sys.argv[1]
FORECAST_START = sys.argv[2]   # "YYYY-MM-DD HH:MM:SS"
HORIZON_H   = int(sys.argv[3])

# ── colours ──────────────────────────────────────────────────────────────────
import os, shutil
USE_COLOR = sys.stdout.isatty() and shutil.get_terminal_size().columns > 0
def c(code, s): return f"\033[{code}m{s}\033[0m" if USE_COLOR else s
BOLD  = lambda s: c("1",   s)
GREEN = lambda s: c("32",  s)
CYAN  = lambda s: c("36",  s)
RED   = lambda s: c("31",  s)
YELLOW= lambda s: c("33",  s)
DIM   = lambda s: c("2",   s)

def ok(msg):   print(f"    {GREEN('✓')}  {msg}")
def bad(msg):  print(f"    {RED('✗')}  {msg}")
def info(msg): print(f"    {CYAN('·')}  {msg}")

# ── parse the forecast start datetime ────────────────────────────────────────
from datetime import datetime, timedelta
t0 = datetime.strptime(FORECAST_START, "%Y-%m-%d %H:%M:%S")

def dt_str(offset_h, offset_min=0):
    return (t0 + timedelta(hours=offset_h, minutes=offset_min)).strftime(
        "%Y-%m-%d %H:%M:%S")

# ── queries to send ───────────────────────────────────────────────────────────
# Each entry: (label, command_string)
# The last query is intentionally outside the forecast window to show error handling.
queries = [
    ("Ping",                                        "ping"),
    ("Hold  t+24 h  LST=10.5 lat=25.0 alt=400 km", f"hold   {dt_str(24)}  10.5  25.0  400.0"),
    ("Interp t+24.5h LST=10.5 lat=25.0 alt=400 km",f"interp {dt_str(24, 30)}  10.5  25.0  400.0"),
    ("Interp t+48 h  LST=18.0 lat=45.0 alt=300 km",f"interp {dt_str(48)}  18.0  45.0  300.0"),
    ("Interp t+72 h  LST=0.0  lat=-30.0 alt=600 km",f"interp {dt_str(72)}   0.0 -30.0  600.0"),
    ("Interp t+96 h  LST=6.0  lat=60.0 alt=200 km", f"interp {dt_str(96)}   6.0  60.0  200.0"),
    ("Interp t+119h  LST=22.0 lat=-60.0 alt=980 km",f"interp {dt_str(119)} 22.0 -60.0  980.0"),
    ("OUT-OF-RANGE (t+200 h, expect error)",         f"interp {dt_str(200)}  10.5  25.0  400.0"),
    ("Quit",                                         "quit"),
]

# ── connect ───────────────────────────────────────────────────────────────────
print(f"    Connecting to {SOCK_PATH}")
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
sock.connect(SOCK_PATH)
sock.settimeout(10.0)
f = sock.makefile("rwb")

def send(cmd):
    f.write((cmd.strip() + "\n").encode())
    f.flush()

def recv():
    return f.readline().decode().rstrip("\r\n")

# ── run queries ───────────────────────────────────────────────────────────────
print()
COL_LABEL = 52
COL_RESP  = 24
print(f"    {BOLD('Query'):<{COL_LABEL}}  {BOLD('Response')}")
print(f"    {'-' * (COL_LABEL + COL_RESP + 2)}")

n_ok = 0
n_err = 0
for label, cmd in queries:
    send(cmd)
    t_send = time.monotonic()
    resp = recv()
    elapsed_ms = (time.monotonic() - t_send) * 1000

    is_ok    = resp.startswith("ok") or resp in ("pong", "bye")
    is_err   = resp.startswith("err")
    is_oor   = "out_of_range" in resp

    # Format response for display
    if resp.startswith("ok "):
        density = float(resp.split()[1])
        resp_display = f"density = {density:.4e} kg/m³"
    else:
        resp_display = resp

    timing = DIM(f"  ({elapsed_ms:.1f} ms)")

    if is_oor:
        # Expected error — show in yellow
        print(f"    {YELLOW(label):<{COL_LABEL}}  {YELLOW(resp_display)}{timing}")
        n_ok += 1   # this was the intended outcome
    elif is_ok:
        print(f"    {label:<{COL_LABEL}}  {GREEN(resp_display)}{timing}")
        n_ok += 1
    else:
        print(f"    {RED(label):<{COL_LABEL}}  {RED(resp_display)}{timing}")
        n_err += 1

print()
print(f"    {n_ok} succeeded  ·  {n_err} unexpected errors")

sock.close()

if n_err > 0:
    sys.exit(1)
PYEOF

echo ""
ok "All queries completed."
echo ""

# ===========================================================================
# Step 5 — Stop the container and clean up
# ===========================================================================
step 5 "Shut down"

info "Sending SIGTERM to container '${CONTAINER_NAME}'..."
docker stop --time 5 "${CONTAINER_NAME}" >/dev/null
ok "Container stopped."
info "Removing temporary files..."
rm -rf "${TMPDIR_DEMO}"
TMPDIR_DEMO=""
ok "Cleaned up."

echo ""
echo "${C_BOLD}${C_GREEN}Demo complete.${C_RESET}"
echo ""
